# Model arguments
model_name_or_path: rkumar1999/Llama-3.1-8B-Instruct-Open-R1-Distill
model_revision: main
torch_dtype: half
attn_implementation: flash_attention_2

# Data training arguments
dataset_name: rkumar1999/numina-deepseek-r1-qwen-7b-1000
dataset_configs:
- all
# Num processes is less by 1 as vLLM is using 1 GPU
num_processes: 1

# GRPO trainer config
bf16: true
use_vllm: true
vllm_device: auto
vllm_gpu_memory_utilization: 0.7
do_eval: true
eval_strategy: steps
eval_steps: 100
gradient_accumulation_steps: 32
gradient_checkpointing: true
gradient_checkpointing_kwargs:
  use_reentrant: false
hub_model_id: Llama-3.1-8B-Instruct-Open-R1-Distill-GRPO
hub_strategy: every_save
learning_rate: 2.0e-05
log_level: info
logging_steps: 100
logging_strategy: steps
lr_scheduler_type: cosine
max_prompt_length: 512
max_completion_length: 1024
max_steps: -1
num_generations: 4
num_train_epochs: 1
output_dir: data/Llama-3.1-8B-Instruct-Open-R1-Distill-GRPO
overwrite_output_dir: true
per_device_eval_batch_size: 64
per_device_train_batch_size: 32
push_to_hub: true
report_to:
- wandb
save_strategy: "no"
seed: 42
warmup_ratio: 0.1
